version: "3"
services:
    webapp:
            container_name: testapp
            restart: always
            build: .
            ports:
                - "5000:3000"
            links:
                - mongo   
            volumes:
                - .:/usr/src/app 
    mongo:
            container_name: mongodb
            image: mongo
            ports:
                - "27017:27017"
            logging:
              driver: none